### ISSUE TITLE
Import into NextJs

### ISSUE THREAD

**Issue by SalamanderHP** [IronCoreLabs/recrypt-node-binding#121]
HI, i'm trying to import this node-binding into my NextJs project to run, but it keeps tlling me this error: ./node_modules/@ironcorelabs/recrypt-node-binding/bin-package/index.node
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

Please show me the proper way to import into framework like NextJs, thanks

**Comment by skeet70** [comment]
We don't use NextJS, so I'm not sure how to load a node binary in NextJS. This is an issue specific to your individual bundling ecosystem, not this library. 

Based on the error you're getting and webpack use, you/NextJS may be trying to bundle `recrypt-node-binding` for the browser, which won't work. In our direct usage of the library in another node library we didn't have to do anything special and in others use of the library with webpack they didn't have to do anything special. I tried googling your issue for you and found [this nextjs issue](https://github.com/vercel/next.js/discussions/34040) which may help get you headed in the right direction.

I'm going to close this issue since it's not related to our library, but if you'd like more conversational help you could try asking in one of our [community](https://ironcorelabs.com/community/) channels.
